name: internetshop-pipeline

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:

  build:

    runs-on: windows-latest

    env:
      Solution_Name: Backend/Src/Shop.sln
      Test_Project_Path: Backend/Src/ShopWebApi/ShopWebApi.csproj

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Restore NuGet Packages
        run: dotnet restore ${{ env.Solution_Name }}

      - name: Build solution
        run: msbuild ${{ env.Solution_Name }} /t:Build /p:OutDir=Backend\Artifacts

  deploy:

    needs: build
    runs-on: windows-latest

    steps:
      - name: Package into Zip
        run: |
          New-Item -ItemType Directory -Force -Path Backend\Artifacts
          Compress-Archive -Path Backend\Artifacts -DestinationPath "$(Get-Location)\Backend\Artifacts\artifacts.zip"
        shell: pwsh


      - name: Publish Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: Backend\Artifacts\artifacts.zip
