name: internetshop-pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest  


    env:
      Solution_Name: Backend/Src/Shop.sln                    
      Test_Project_Path: Backend/Src/ShopWebApi/ShopWebApi.csproj                

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Restore NuGet Packages
      run: dotnet restore Backend/Src/Shop.sln 

    - name: Restore the application
      run: msbuild Backend/Src/Shop.sln 
      env:
        Configuration: ${{ matrix.configuration }}
        
    - name: Build solution
      run: msbuild Backend/Src/Shop.sln 
